version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_ASSET_PATH=/assets
    command: node ./src/server.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  proxy:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 3001:80
    command: nginx -g 'daemon off;'
    depends_on:
      - server
      - frontend
