version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_ASSET_PATH=/assets
    command: node ./src/server.js
    depends_on:
      - redis
    restart: always
  redis:
    image: redislabs/rejson
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - ./frontend/dist:/app/dist
    restart: always
  proxy:
    image: nginx
    volumes:
    - ./nginx/default.selfhost.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 3001:80
    command: nginx -g 'daemon off;'
    restart: always
    depends_on:
      - server
      - frontend
