version: '3.7'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
    - ./backend/src:/app/src
    environment:
      - FRONTEND_ASSET_PATH=/assets
      - MONGODB_URI=mongodb://root:DBPASS_CHANGEME@mongo:27017/openretro
    depends_on:
      - redis
  redis:
    image: redislabs/rejson
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: DBPASS_CHANGEME
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/dist:/app/dist
  proxy:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/dist:/usr/share/nginx/html/assets
    ports:
    - 3001:80
    command: nginx -g 'daemon off;'
    depends_on:
      - server
      - frontend
